### ISSUE TITLE
打包遗漏 Emoji 字体

### ISSUE THREAD

**Issue by IAliceBobI** [TCOTC/siyuan-ttf-HarmonyOS_Sans_SC-and-Twemoji#1]
感谢提供插件。

浏览器内用，有报错，没这个资源。用插件api，  confirm 时出现。

```
import {  confirm  } from "siyuan";


GET http://localhost:6806/plugins/siyuan-ttf-HarmonyOS_Sans_SC-and-Twemoji/Twemoji-15.1.0.ttf         net::ERR_ABORTED 404 (Not Found)
```

![image](https://github.com/user-attachments/assets/3b3c6e24-fc5d-4778-a7a4-65cf65b18b9e)

**Comment by IAliceBobI** [comment]
刚刚安装完插件，就能看到。
桌面端的思源。


https://github.com/user-attachments/assets/164a8c42-a8ce-47af-8edd-a02e3d8aacaa

**Comment by TCOTC** [comment]
感谢提醒，上次换字体文件导致打包遗漏了 Emoji 字体，下个版本补上
